on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
name: unit test
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.20', '1.21' ]
    name: Go ${{ matrix.go }} test
    steps:
      - uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - name: test
        run: go test -v -race ./...
